app/lib/waypoints_direct_web/router.ex
defmodule WaypointsDirectWeb.Router do
  use WaypointsDirectWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  require Ueberauth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :secure do
    plug WaypointsDirect.Plug.Secure
  end

  scope "/", WaypointsDirectWeb do
    pipe_through :browser

    get "/", LandingController, :index
  end

  scope "/auth", WaypointsDirectWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/routes", WaypointsDirectWeb do
    pipe_through :browser

    get "/", RouteController, :index
  end

  scope "/management", WaypointsDirectWeb do
    pipe_through [:browser, :secure]

    get "/logout", AuthController, :logout
  end

  scope "/management/routes", WaypointsDirectWeb do
    pipe_through [:browser, :secure]

    get "/new", RouteManagementController, :new
  end

  scope "/api/routes", WaypointsDirectWeb do
    pipe_through :api

    resources "/", RouteApiController
  end
  
  scope "/api/intersections", WaypointsDirectWeb do
    pipe_through :api

    resources "/", IntersectionApiController
  end

  scope "/api/graph", WaypointsDirectWeb do
    pipe_through :api

    get "/search_path", GraphApiController, :search_path
  end

  # Other scopes may use custom stacks.
  # scope "/api", WaypointsDirect do
  #   pipe_through :api
  # end
end

app/lib/waypoints_direct_web/controllers/route_controller.ex
defmodule WaypointsDirectWeb.RouteController do
    use WaypointsDirectWeb, :controller

    def index(conn, _params) do
        render conn, :index
    end
end

app/lib/waypoints_direct_web/views/route_view.ex
defmodule WaypointsDirectWeb.RouteView do
    use WaypointsDirectWeb, :view

    import WaypointsDirectWeb.BaseViewHelper
end

app/lib/waypoints_direct_web/templates/route/index.html.eex
<div class="module-route-index">
    <div id="app-root"></div>
</div>

<script>
	GOOGLE_MAP_API_KEY = "<%= googleMapApiKey() %>";
	APP_LOGO = "<%= static_path(@conn, "/images/jeepney_logo_beta.png") %>";
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= googleMapApiKey() %>"></script>
<script src="<%= static_path(@conn, "/lib/raven-3.22.3.min.js") %>"></script>
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>

<script>
    PAGE_ROUTES = {
        "ROUTE_API_INDEX": "<%= route_api_path(@conn, :index) %>",
        "INTERSECTION_API_INDEX": "<%= intersection_api_path(@conn, :index) %>",
		"GRAPH_API_SEARCH_PATH": "<%= graph_api_path(@conn, :search_path) %>",
    };

	Raven.config('<%= sentryFrontendDsn() %>').install()

	function ready() {
		Raven.context(function () {
			require("js/routes/index/main.js");
		});
	}

	if (document.readyState === "complete" || document.readyState !== "loading") {
		ready();
	} else {
		document.addEventListener("DOMContentLoaded", ready);
	}
</script>

app/lib/waypoints_direct_web/templates/route/show.html.eex
<div class="show">
    <div class="columns">
        <div class="column">
            <div id="map"></div>
        </div>
    </div>

    <div class="container">
        <div class="content">
            <h1 class="title"><%= @route.description %></h1>
        </div>
    </div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB11S8LbcWKHxQPT08a3vxhlvOqONbL_x4"></script>

<script>
    function ready() {
        require("route/show.js").default(<%= @route.id %>)
    }

    if (document.readyState === "complete" || document.readyState !== "loading") {
        ready();
    } else {
        document.addEventListener("DOMContentLoaded", ready);
    }
</script>